# Generated by Django 4.2.7 on 2023-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='noimage.jpg', upload_to='profile_images'),
        ),
    ]
